# Generated by Django 3.0.5 on 2020-06-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_userblocking'),
        ('home', '0002_auto_20200605_1848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
